name: Deploy to cPanel
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # The directory to deploy (root of your repo)
          server-dir: /bonapi.reownlogics.com/  # The directory on your cPanel server
